# Data

Sleep data will primarily be drawn from the Center for Disease Control and Prevention (http://www.cdc.gov/places/) and population demographic data from the U.S. Census Bureau (https://data.census.gov/all/tables).

## Description

**Population Demographics: Race and Socioeconomic Data**
These data are available on the U.S. Census Bureau website, they just have to properly be queried at the zipcode tabulation area (ZCTA) level which ended up being more time consuming than initially planned because I could not find a way to get it at the ZCTA level without having to manually select/filter all the ZCTAs that fall within NYC. If you try to filter by county for instance, it will only give you the population demographics aggregated at the county level vs. ZCTA, which would not match our unit of analysis. This will be sorted soon! The good thing is there is a clear concrete plan and the data is there in a unit similar to to the sleep data (percentage or prevalence per ZCTA).

**Sleep Data Over Time**
Sleep data are obtained from the CDC’s PLACES Local Data for Better Health datasets directly from the CDC website (Center for Disease Control and Prevention, 2020, 2023, 2024). The PLACES datasets are created with ZCTA-level estimates derived from data collected through the nationally representative annual U.S. Behavioral Risk Factor Surveillance Survey (BRFSS). The BRFSS is an annual, phone-based survey of the US population who are 18 years and older. The CDC works with local state health department to interview respondents. Every other year, the BRFSS includes a question asking “On average, how many hours of sleep do you get in a 24-hour period?”. 

Using the BRFSS data, an estimate is created for the percentage of the population (per ZCTA) that reports sleeping < 7 hours on average. Population data used to help model these estimates were drawn from the American Community Surveys (ACS) for each of the respective BRFSS years (2018, 2020, 2022). The ACS is collected and managed by the U.S. Census Bureau. Because sleep data is only collected every other year and PLACES short sleep prevalence estimates are created using the most recent year with available data (even if the year the data were collected does not align with the release year of the PLACES dataset) I plan to use the PLACES datasets for the years 2020, 2023, 2024 which created estimates for sleep using BRFSS data from 2018, 2020, and 2022. respectively (Center for Disease Control and Prevention, 2020, 2023 & 2024). 

## Missing value analysis

Because each row of the sleep data is a model estimated value, there actually aren't any NAs in this dataset, however once I merge the Bureau demographic data, I anticipate NAs will be introduced simply by mismatched or unmatched ZTCAs.

My plan for the final project is that once these datsets are properly merged, I will do a proper pivot longer and create a "missing" data column and do a geom_tile plot to visualize the missing data. I am thinking to do 1 missing data plot per year so as to not overcrowd the visual.




